name: CI

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  laravel-tests:
    strategy:
      matrix:
        target: ['8.2', '8.3']

    runs-on: php-alpine-${{ matrix.target }}

    services:
      mariadb:
          image: mariadb:lts@sha256:272084c2dec70619714df329c4ffcb336e3f8c723072c3f56f2e4015997bbf2c
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: mundialis_test
          ports:
              - 3306
          options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Install dependencies
      uses: https://code.itinerare.net/internal/laravel-setup-action@main
      with:
        composer-auth: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Run tests
      run: php artisan test
      env:
        DB_HOST: mariadb

  laravel-tests-sqlite:
    strategy:
      matrix:
        target: ['8.2', '8.3']

    runs-on: php-alpine-${{ matrix.target }}

    steps:
    - name: Install dependencies
      uses: https://code.itinerare.net/internal/laravel-setup-action@main
      with:
        composer-auth: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Run tests
      run: php artisan test -c phpunit-sqlite.xml

  pint:
    runs-on: php-alpine-8.2
    needs: laravel-tests

    steps:
    - name: Install dependencies
      uses: https://code.itinerare.net/internal/php-setup-action@main
      with:
        composer-auth: ${{ secrets.COMPOSER_AUTH_JSON }}

    - name: Run pint
      run: composer lint

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'refactor: fix PHP styling'
        gpg_key: ${{ secrets.CI_GPG }}

    - name: Organize logs
      run: echo "Complete!"

  blade-formatter:
    runs-on: node-alpine
    needs: laravel-tests

    steps:
    - name: Install dependencies
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run blade-formatter
      run: npm run format

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'refactor: fix blade formatting'
        gpg_key: ${{ secrets.CI_GPG }}

    - name: Organize logs
      run: echo "Complete!"

  rebuild-mix-assets:
    runs-on: node-alpine
    needs: laravel-tests

    steps:
    - name: Install dependencies
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run Mix
      run: npm run prod

    - name: Commit changes
      uses: https://code.itinerare.net/internal/lint-commit-action@main
      with:
        message: 'chore(deps): rebuild mix assets'
        gpg_key: ${{ secrets.CI_GPG }}

    - name: Organize logs
      run: echo "Complete!"
