name: Lint & Build Mix Assets

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pint:
    runs-on: docker

    steps:
    - name: Set up PHP
      uses: https://github.com/shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install dependencies
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

    - name: Run pint
      run: composer lint

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
          message: 'refactor: fix PHP styling'
          default_author: github_actions
          author_name: Amadeus[bot]
          author_email: amadeus@itinerare.net

  blade-formatter:
    runs-on: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up node
      uses: https://github.com/actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'

    - name: Install packages
      run: npm install

    - name: Run blade-formatter
      run: npm run format

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
          pull: '--rebase --autostash'
          message: 'refactor: fix blade formatting'
          default_author: github_actions
          author_name: Amadeus[bot]
          author_email: amadeus@itinerare.net

  rebuild-vite-assets:
    runs-on: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up node
      uses: https://github.com/actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        cache: 'npm'

    - name: Install packages
      run: npm install

    - name: Run Mix
      run: npm run prod

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
          pull: '--rebase --autostash'
          message: 'chore(deps): rebuild mix assets'
          default_author: github_actions
          author_name: Amadeus[bot]
          author_email: amadeus@itinerare.net
