name: CI

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  laravel-tests:
    strategy:
      matrix:
        target: ['8.2', '8.3']

    runs-on: docker

    services:
      mysql:
          image: mysql:9
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: mundialis_test
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Set up PHP/Laravel
      uses: https://code.itinerare.net/internal/laravel-setup-action@main
      with:
        php-version: ${{ matrix.target }}

    - name: Run tests
      run: php artisan test
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}

  pint:
    runs-on: docker
    needs: laravel-tests

    steps:
    - name: Set up PHP
      uses: https://code.itinerare.net/internal/php-setup-action@main
      with:
        php-version: '8.2'

    - name: Run pint
      run: composer lint

    - name: Import GPG key
      uses: https://github.com/crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.CI_GPG }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
        message: 'refactor: fix PHP styling'
        default_author: github_actions
        author_name: ${{ vars.COMMITTER_NAME }}
        author_email: ${{ vars.COMMITTER_EMAIL }}

  blade-formatter:
    runs-on: docker
    needs: laravel-tests

    steps:
    - name: Set up node/npm
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run blade-formatter
      run: npm run format

    - name: Import GPG key
      uses: https://github.com/crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.CI_GPG }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
        pull: '--rebase --autostash'
        message: 'refactor: fix blade formatting'
        default_author: github_actions
        author_name: ${{ vars.COMMITTER_NAME }}
        author_email: ${{ vars.COMMITTER_EMAIL }}

  rebuild-mix-assets:
    runs-on: docker
    needs: laravel-tests

    steps:
    - name: Set up node/npm
      uses: https://code.itinerare.net/internal/node-setup-action@main

    - name: Run Mix
      run: npm run prod

    - name: Import GPG key
      uses: https://github.com/crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.CI_GPG }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      uses: https://github.com/EndBug/add-and-commit@v9
      with:
          pull: '--rebase --autostash'
          message: 'chore(deps): rebuild mix assets'
          default_author: github_actions
          author_name: ${{ vars.COMMITTER_NAME }}
          author_email: ${{ vars.COMMITTER_EMAIL }}
