name: Deploy to demo site

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: docker

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd "${{ vars.DEPLOY_APP_PATH }}"
          php artisan down --render="errors::503" --refresh=30
          git pull
          composer install -no --no-dev --ignore-platform-reqs
          php artisan migrate --force
          php artisan optimize
          php artisan optimize
          php artisan app:add-site-settings
          php artisan up
          ENDSSH
