name: Laravel Tests

on:
  push:
    branches:
      - '**'

jobs:
  laravel-tests:
    strategy:
      matrix:
        target: ['8.1', '8.2']

    runs-on: docker

    steps:
    - name: Set up PHP
      uses: https://github.com/shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.target }}
        extensions: gd, imagick

    - name: Checkout code
      uses: https://code.itinerare.net/internal/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install dependencies
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}
      run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run tests
      run: php artisan test
      env:
        DB_HOST: ${{ vars.MYSQL_HOST }}
        DB_PORT: 3306
        DB_DATABASE: mundialis_test
        DB_USERNAME: forgejo_runner
        DB_PASSWORD: ${{ secrets.MYSQL_PASS }}
